Radiant Sand Dog

medium

# Users might not be able to withdraw as many assets as they should if destination vault is at a loss
## Summary

On user withdrawal, if vaults are at a loss, the proportional amount of shares the user can burn in the destination vaults is calculated based on the amount of shares to be burned, and not on the total shares owned by the user, which might result in the user not being able to withdraw the amount of assets they wanted to.

## Vulnerability Detail

When a user withdraws assets from `LMPVault` via `withdraw()` or `redeem()` and the amount of idle assets is not enough to cover the withdrawal, shares are burned from destination vaults, and assets are pulled from the destination vaults to cover the withdrawal.

The calculation of the amount of shares to burn is done in `_calcUserWithdrawSharesToBurn()`. As we can read in the comments when the deployment of the vault is at a loss:

> they can only burn an amount proportional to their ownership of this vault. This is so a user doesn't lock in a loss for the entire vault during their withdrawal

This is reflected in the code:

```solidity
File: LMPDebt.sol

275        if (currentDvDebtValue < updatedDebtBasis) {
276            // We are currently sitting at a loss. Limit the value we can pull from
277            // the destination vault
278            currentDvDebtValue = currentDvDebtValue.mulDiv(userShares, totalVaultShares, Math.Rounding.Down);
279            currentDvShares = currentDvShares.mulDiv(userShares, totalVaultShares, Math.Rounding.Down);
280        }
```

The issue is that `_calcUserWithdrawSharesToBurn()` is not receiving the total shares owned by the user, but the number of shares to be burned.

```solidity
File: LMPVault.sol

400    function withdraw(
401        uint256 assets,
402        address receiver,
403        address owner
404    ) public virtual override nonReentrant noNavDecrease ensureNoNavOps returns (uint256 shares) {
405        Errors.verifyNotZero(assets, "assets");
406        uint256 maxAssets = maxWithdraw(owner);
407        if (assets > maxAssets) {
408            revert ERC4626ExceededMaxWithdraw(owner, assets, maxAssets);
409        }
410
411        // query number of shares these assets match
412        shares = previewWithdraw(assets); ðŸ‘ˆ
413
414        uint256 actualAssets = _withdraw(assets, shares, receiver, owner); ðŸ‘ˆ
    (...)
448    function _withdraw(
449        uint256 assets,
450        uint256 shares, ðŸ‘ˆ
451        address receiver,
452        address owner
453    ) internal virtual returns (uint256) {
   (...)
472                (uint256 sharesToBurn, uint256 totalDebtBurn) = _calcUserWithdrawSharesToBurn(
473                    destVault,
474                    shares, ðŸ‘ˆ
475                    info.totalAssetsToPull - Math.max(info.debtDecrease, info.totalAssetsPulled),
476                    totalVaultShares
477                );
```

As a result, the amount of shares the user can burn in the destination vault is a proportion of the shares to be burned, not the total shares owned by the user. In case the destination vaults that are at a loss suppose a significant portion of the total vault shares, the user might not be able to withdraw the amount of assets they wanted to.

## Impact

On user withdrawal, if vaults are at a loss, users might not be able to withdraw the amount they wanted to.

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L474

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/libs/LMPDebt.sol#L275-L280

## Proof of concept

Do the following change in `LMPVault-Withdraw.t.sol:_assertResults()` to reflect the real value that will be passed to `_calcUserWithdrawSharesToBurn()`:

```diff
        (uint256 sharesToBurn, uint256 expectedTotalBurn) = _lmpVault.calcUserWithdrawSharesToBurn(
            IDestinationVault(dv),
-           testInfo.userShares,
+           testInfo.expectedSharesToBurn,
            testInfo.assetsToPull,
            testInfo.totalAssetsPulled,
            testInfo.totalSupply
        );
```

Run tests for withdrawal with destination vaults at a loss:

```shell
forge test --mt testAtLoss -vv
```

We can see that some of the tests fail, as the user is not able to withdraw the amount of assets they wanted to:

```shell
[FAIL. Reason: Assertion failed.] testAtLossComplexPricingLowerCurrentShares() (gas: 140501)
Logs:
  Error: sharesToBurn
  Error: a == b not satisfied [uint]
    Expected: 27
      Actual: 24
  Error: expectedTotalBurn
  Error: a == b not satisfied [uint]
    Expected: 46
      Actual: 41

[FAIL. Reason: Assertion failed.] testAtLossUserPortionWontCover() (gas: 140478)
Logs:
  Error: sharesToBurn
  Error: a == b not satisfied [uint]
    Expected: 90
      Actual: 81
  Error: expectedTotalBurn
  Error: a == b not satisfied [uint]
    Expected: 36
      Actual: 33
```

## Tool used

Manual Review

## Recommendation

```diff
diff --git a/src/vault/LMPVault.sol b/src/vault/LMPVault.sol

    (uint256 sharesToBurn, uint256 totalDebtBurn) = _calcUserWithdrawSharesToBurn(
        destVault,
-       shares,
+       balanceOf(owner),
        info.totalAssetsToPull - Math.max(info.debtDecrease, info.totalAssetsPulled),
        totalVaultShares
    );
```